#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "profile_store.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ACX_PROFILE_FILE_EXTENSION ".acx"
#define ACX_PROFILE_PACKAGE_TAG "ACX1"
#define ACX_PROFILE_MAGIC_BYTES "ACX1"

#define ACX_PROFILE_FORMAT_VERSION 1U
#define ACX_PROFILE_HEADER_SIZE 64U
#define ACX_PROFILE_SECTION_DIRECTORY_ENTRY_SIZE 24U
#define ACX_PROFILE_MAX_SECTION_COUNT 8U
#define ACX_PROFILE_REQUIRED_SECTION_COUNT 8U
#define ACX_PROFILE_TRANSPORT_MAX_BYTES 65536U
#define ACX_PROFILE_PAYLOAD_OFFSET ACX_PROFILE_HEADER_SIZE
#define ACX_PROFILE_SECTION_VERSION_SUPPORTED 1U

#define ACX_PROFILE_MAX_FILENAME_LEN APP_PROFILE_MAX_FILENAME_LEN
#define ACX_PROFILE_MAX_PROFILE_NAME_LEN APP_PROFILE_MAX_PROFILE_NAME_LEN
#define ACX_PROFILE_MAX_SYSTEM_LEN APP_PROFILE_MAX_SYSTEM_LEN
#define ACX_PROFILE_MAX_INIT_SCRIPT_LEN APP_PROFILE_MAX_INIT_SCRIPT_LEN
#define ACX_PROFILE_MAX_ACTION_NAME_LEN APP_PROFILE_MAX_ACTION_NAME_LEN
#define ACX_PROFILE_MAX_LINE_LEN APP_PROFILE_MAX_LINE_LEN
#define ACX_PROFILE_MAX_ACTIONS APP_PROFILE_MAX_ACTIONS
#define ACX_PROFILE_MAX_COMMANDS APP_PROFILE_MAX_COMMANDS
#define ACX_PROFILE_COMMAND_TEXT_BYTES APP_PROFILE_COMMAND_TEXT_BYTES
#define ACX_PROFILE_MAX_WAIT_MS APP_PROFILE_MAX_WAIT_MS
#define ACX_PROFILE_MAX_INIT_STEPS APP_PROFILE_MAX_INIT_STEPS
#define ACX_PROFILE_INIT_TEXT_BYTES APP_PROFILE_INIT_TEXT_BYTES
#define ACX_PROFILE_MAX_MOTION_SEQUENCE APP_PROFILE_MAX_MOTION_SEQUENCE
#define ACX_PROFILE_MAX_POSITIONS APP_PROFILE_MAX_POSITIONS
#define ACX_PROFILE_MAX_YARN_ADDRESSES APP_PROFILE_MAX_YARN_ADDRESSES
#define ACX_PROFILE_MAX_STITCH_ADDRESSES APP_PROFILE_MAX_STITCH_ADDRESSES
#define ACX_PROFILE_MAX_CAN_DLC APP_HEAD_PROFILE_MAX_DLC
#define ACX_PROFILE_MAX_CAN_ID 0x1FFFFFFFU
#define ACX_PROFILE_WORK_BUFFER_BYTES 256U
#define ACX_PROFILE_ACTION_TRACKING_BYTES (ACX_PROFILE_MAX_ACTIONS * (ACX_PROFILE_MAX_ACTION_NAME_LEN + 1U))
#define ACX_PROFILE_TEMP_BUFFER_MAX_BYTES (ACX_PROFILE_WORK_BUFFER_BYTES + ACX_PROFILE_ACTION_TRACKING_BYTES)

typedef enum {
    ACX_PROFILE_SECTION_METADATA = 1U,
    ACX_PROFILE_SECTION_INIT = 2U,
    ACX_PROFILE_SECTION_TESTEO = 3U,
    ACX_PROFILE_SECTION_MOTION = 4U,
    ACX_PROFILE_SECTION_J = 5U,
    ACX_PROFILE_SECTION_CASCADE = 6U,
    ACX_PROFILE_SECTION_STOP = 7U,
    ACX_PROFILE_SECTION_ACTIONS = 8U,
} AcxProfileSectionId;

typedef enum {
    ACX_PROFILE_LOAD_OK = 0,
    ACX_PROFILE_LOAD_ERROR_INVALID_ARGUMENT,
    ACX_PROFILE_LOAD_ERROR_INVALID_PATH,
    ACX_PROFILE_LOAD_ERROR_FILE_NOT_FOUND,
    ACX_PROFILE_LOAD_ERROR_FILE_TOO_SMALL,
    ACX_PROFILE_LOAD_ERROR_FILE_TOO_LARGE,
    ACX_PROFILE_LOAD_ERROR_INVALID_MAGIC,
    ACX_PROFILE_LOAD_ERROR_UNSUPPORTED_VERSION,
    ACX_PROFILE_LOAD_ERROR_INVALID_HEADER,
    ACX_PROFILE_LOAD_ERROR_INVALID_DIRECTORY,
    ACX_PROFILE_LOAD_ERROR_UNSUPPORTED_SECTION_VERSION,
    ACX_PROFILE_LOAD_ERROR_DUPLICATE_SECTION,
    ACX_PROFILE_LOAD_ERROR_MISSING_SECTION,
    ACX_PROFILE_LOAD_ERROR_INVALID_OFFSET,
    ACX_PROFILE_LOAD_ERROR_OVERLAPPING_SECTIONS,
    ACX_PROFILE_LOAD_ERROR_INVALID_RECORD,
    ACX_PROFILE_LOAD_ERROR_INVALID_COUNT,
    ACX_PROFILE_LOAD_ERROR_INVALID_STRING,
    ACX_PROFILE_LOAD_ERROR_RESERVED_NONZERO,
    ACX_PROFILE_LOAD_ERROR_PAYLOAD_CRC_MISMATCH,
    ACX_PROFILE_LOAD_ERROR_SECTION_CRC_MISMATCH,
    ACX_PROFILE_LOAD_ERROR_RUNTIME_CAPACITY_EXCEEDED,
    ACX_PROFILE_LOAD_ERROR_IO_ERROR,
    ACX_PROFILE_LOAD_ERROR_INVALID_ENDIANNESS,
} AcxProfileLoadError;

typedef struct {
    AcxProfileLoadError error;
    char message[160];
    char file_name[ACX_PROFILE_MAX_FILENAME_LEN + 1];

    uint32_t file_size;
    uint32_t header_size;
    uint32_t payload_offset;
    uint32_t payload_size;
    uint32_t section_directory_size;
    uint16_t section_count;
    uint32_t declared_payload_crc32;
    uint32_t computed_payload_crc32;
    uint32_t temp_buffer_max;

    uint16_t total_actions;
    uint16_t enabled_actions;
    uint16_t materialized_actions;
    uint32_t materialized_commands;
    uint32_t command_text_bytes;
    uint32_t init_text_bytes;

    uint16_t failing_section_id;
    uint16_t failing_section_version;
    uint32_t failing_offset;
    uint32_t failing_size;
    uint32_t failing_record_count;

    bool profile_enabled;
    bool profile_published;
    bool has_source_crc32;
    uint8_t source_kind;
    uint32_t source_crc32;
    uint32_t profile_id;
    uint32_t profile_version_id;
    int32_t program_number;
    int32_t version_number;
    uint32_t schema_version;

    char profile_key[ACX_PROFILE_MAX_FILENAME_LEN + 1];
    char display_name[ACX_PROFILE_MAX_PROFILE_NAME_LEN + 1];
} AcxProfileLoadResult;

const char *app_acx_profile_load_error_text(AcxProfileLoadError error);

#ifdef __cplusplus
}
#endif
